# Generated by Django 4.1 on 2022-09-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStore', '0002_products_created_products_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
